# local
baiduqianxi:
    mongo:
        host: 192.168.0.235
        port: 27017
        db: baiduqianxi
        collection: baiduqianxi
baidubaike:
    mongo:
        host: 192.168.0.235
        port: 27017
        db: baike
        collection: baike_test

## online
#baiduqianxi:
#    mongo:
#        host: 192.168.0.235
#        port: 27017
#        db: baiduqianxi
#        collection: baiduqianxi_test
#baidubaike:
#    mongo:
#        host: 192.168.0.235
#        port: 27017
#        db: baike
#        collection: baike
